### ISSUE TITLE
Spack cannot find poesie package

### ISSUE THREAD

**Issue by dyokelson** [mochi-hpc/mochi-poesie#1]
Hello! I was trying to install poesie to see if I can use it for a research project but spack is unable to find it. I tried on a couple of different machines and also ran some spack cleans. I have attached some of my steps below as well as the errors. Do you know if it is still available for installation through spack? Or perhaps I am missing something, thanks!

[dewiy@delphi spack]$ spack install poesie
==> Error: Package 'poesie' not found.
You may need to run 'spack clean -m'.
[dewiy@delphi spack]$ spack clean -m
==> Removing cached information on repositories
[dewiy@delphi spack]$ spack install poesie
==> Error: Package 'poesie' not found.
You may need to run 'spack clean -m'.
[dewiy@delphi spack]$ spack clean -a
==> Removing all temporary build stages
==> Removing cached downloads
==> Removing install failure marks
==> Removing cached information on repositories
==> Removing python cache files
[dewiy@delphi spack]$ spack install poesie
==> Error: Package 'poesie' not found.
You may need to run 'spack clean -m'.

**Comment by mdorier** [comment]
All the mochi libraries are available via [mochi-spack-packages](https://github.com/mochi-hpc/mochi-spack-packages), which you can add to spack by doing the following:

```
git clone https://github.com/mochi-hpc/mochi-spack-packages.git
spack repo add mochi-spack-packages
```

Then you can install poesie using `spack install mochi-poesie`.

That said, it is currently broken and hasn't been updated in more than 2 years (simply because we haven't had a use for it so far and nobody has expressed an interest in using it). If you tell me what you need it for, I can see what I can do.

**Comment by dyokelson** [comment]
Thank you! I already had mochi-spack-packages added so was able to start installation of poesie with `spack install mochi-poesie` however, installation did fail as you mentioned it would. 

We were hoping to use it for project that is similar to/an extension of [SYMBIOMON](https://github.com/srini009/symbiomon). I wanted to try it out to see if it would work for some on-node performance data analysis for the project. Perhaps we can connect over email (dewiy AT uoregon DOT edu) to discuss any options - but I understand if nothing can be done. Thanks!

**Comment by mdorier** [comment]
Sure thing, I'll follow up by email.
